name: Download Docker Logs

on:
  workflow_dispatch:

jobs:
  fetch-logs:
    runs-on: ubuntu-latest

    steps:

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Generate logs on server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        
        mkdir -p /home/ubuntu/logs
        docker ps --format "{{.Names}}" > /home/ubuntu/container_list.txt

        for c in $(cat /home/ubuntu/container_list.txt); do
          echo "Saving logs for $c"
          docker logs $c > /home/ubuntu/logs/$c.log 2>&1
        done

        cd /home/ubuntu
        tar -czf logs.tar.gz logs
        EOF

    - name: Download logs from server
      run: |
        mkdir -p logs
        scp -o StrictHostKeyChecking=no \
        -i ~/.ssh/id_rsa \
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/logs.tar.gz ./logs/

    - name: Extract logs
      run: |
        tar -xzf logs/logs.tar.gz -C logs

    - name: Upload logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-logs
        path: logs/
