name: Download Docker Logs

on:
  workflow_dispatch:

jobs:
  fetch-logs:
    runs-on: ubuntu-latest

    steps:

    - name: Fetch logs from server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p /home/ubuntu/logs
          docker ps --format "{{.Names}}" > container_list.txt

          for c in $(cat container_list.txt); do
            docker logs $c > /home/ubuntu/logs/$c.log 2>&1
          done

          cd /home/ubuntu
          tar -czf logs.tar.gz logs

    - name: Download logs tar from server
      run: |
        mkdir -p logs
        scp -o StrictHostKeyChecking=no \
            -i <(echo "${{ secrets.SERVER_SSH_KEY }}") \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/logs.tar.gz ./logs/

    - name: Extract logs
      run: |
        tar -xzf logs/logs.tar.gz -C logs

    - name: Upload logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-logs
        path: logs/
